version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  goapp:
    build:
      context: ./go-app
    container_name: go-app
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
